### ISSUE TITLE
Gradle Sync Failed

### ISSUE THREAD

**Issue by ceag235** [jgilfelt/android-sqlite-asset-helper#108]
Setting the dependencies to install the helper i get and error

dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
}
-----------------
Error:

Gradle sync failed: Could not find method compile() for arguments [com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
        Consult IDE log for more details (Help | Show Log)

**Comment by Kisty** [comment]
Notice the text underneath:

   // NOTE: Do not place your application dependencies here; they belong
   // in the individual module build.gradle files

Your root `build.gradle` file should look like this:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

Then your app `build.gradle` should look like:

```
dependencies {
    ...
    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
}
```

The reason that warning note was there in the root `build.gradle` is because that's in the buildscript dependencies, not the actual compile dependencies. Hope that makes sense.
