### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by metinkale38** [jgilfelt/android-sqlite-asset-helper#91]
On my Phone i never had problems, but my bug tracker shows following:

 `Caused by java.lang.NullPointerException        at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getWritableDatabase(SQLiteAssetHelper.java:178)        at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:254)`

Seems like it is occuring rare, nothing phone related... 
240 Crashes on 211 Users. So most users got the crash one, and after it it probably worked again...
It happens in different places...

**Comment by Kisty** [comment]
Hmm, strange. Any idea which devices they crash on? What Android versions, etc.?

Do you remember to close the databases when you're done with it? Could be that the database is already open and on some devices it has a stricter policy to manage database operations.

**Comment by metinkale38** [comment]
here are all informations: http://crashes.to/s/c4fe858568a

i always close the database, but it is used in multiple threads. Isnt SqliteDatabaseHelper normally Thread Safe?

**Comment by Kisty** [comment]
Ah, that'd be your problem. [`SQLiteOpenHelper`](http://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html) is not thread-safe if you're writing data to it. I had similar problems and it was because I had multiple instances of [`SQLiteOpenHelper`'s](http://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html)

See http://stackoverflow.com/a/3689883/818821

**Comment by metinkale38** [comment]
then i will close this issue for now, until i upload a thread-safe version to the play store... thank you
