### ISSUE TITLE
Inserting additional records during upgrade

### ISSUE THREAD

**Issue by ritesh2014** [jgilfelt/android-sqlite-asset-helper#97]
I have shipped my database using this library and the database contains some records on table1. Now I want to update my app with a new database with additional records which should be inserted in the one which i already shipped (should not overwrite). I am not sure how exactly to write the SQL scripts for the upgrade since the schema is same for both the databases. Did anyone try this?

**Comment by jon-adams** [comment]
The upgrade script would probably (from what you describe) include some INSERT statements, maybe an UPDATE or two if you need to change anything in the existing records. There isn't anything special about these statements though; just vanilla SQL. (Technically SQLite syntax, but for INSERTS and UPDATES they are pretty much ANSI standard SQL.)

General SQL training is outside the scope of this project though, especially without giving us any specific questions or example data. I recommend browsing StackOverflow and doing a Google search on "SQL INSERT".

**Comment by ritesh2014** [comment]
Well this is not what I asked. Let me elaborate. I created an app with a database through SqliteAssetHelper library. This database contains 100 records. Now in future I want to update my app with a new database which contains additional 50 records. I just want to add these new 50 records in the existing app database which contains 100 records. I DONT want to overwrite the existing database. 
If I write a query like INSERT INTO Destination SELECT * FROM Source; this is not working. I asked this question in stackoverflow - 
http://stackoverflow.com/questions/37262495/android-sqliteassethelper-merging-database-tables-from-asset-with-the-existing
CommonsWare replied that this is currently not possible so I opened a ticket. Hope my explanation is clear now. Is this something that can be implemented?

**Comment by jon-adams** [comment]
_Oh_, now I understand. You have _two_ databases and you want to merge them. Unfortunately there isn't a _direct_ way to do that because this library also uses the same Android pattern of running a _script_ to modify an existing database.

The workaround is to transform your second database (set of 50 records) into 50 INSERT statements that will get put next to the existing 50. (There are various tools all over the internet to simplify that step for you so you don't have to do it by hand.) You said they were the same schema, so as long as the business logic can work with them all together they can all go in the original table, or if you need them separated, use the 50 INSERTs still still but have them INSERT to a different table name instead.

Then, once you have these 50 INSERT statements with the data of the 50 new rows, put the statements in an upgrade script and you can follow the standard library documentation on how to get that script to run via this library.

**Comment by ritesh2014** [comment]
Will it not be easier to just add the records in CSV file, put it in asset folder and then read it into the app database?

**Comment by jon-adams** [comment]
Perhaps. But then you won't get the database version check feature and you'll have to check when to run or not run the code to import that asset file. It's up to you which solution you feel is better for your project.
